version: "3"
services:
  postgres:
    image: postgres:13
    container_name: eth_postgres_db
    env_file:
      - ./secrets/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - eth_postgres_data:/var/lib/postgresql/data
    networks:
      - eth_network

networks:
  eth_network:
    external: False

volumes:
  eth_postgres_data:
